title: Daily ArXiv
description: Selected arXiv papers with meaningful physical insights, concise findings, and original abstracts.
author: northsi
url: https://northsi.github.io
baseurl: /DailyArXiv
theme: jekyll-theme-primer
show_downloads: false
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jemoji
exclude:
  - tests
  - main.py
  - utils.py
  - llm_utils.py
  - paper_cache.json
  - requirements.txt
  - README.md
