name: Update

on:
  workflow_dispatch:
  label:
    types:
      - created # for test
  schedule:
      - cron: '30 16 * * 0-4' # 00:30 Beijing time every Monday to Friday

permissions:
  contents: write
  issues: write 

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update papers
      run: |
        python main.py

    - name: Commit files if changed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "✏️ Update papers automatically."
        file_pattern: |
          README.md
          .github/ISSUE_TEMPLATE.md

    - name: Verify commit & push
      run: |
        echo "----- git status after commit -----"
        git status --porcelain
        echo "----- recent commits -----"
        git log -n 5 --oneline --decorate
        git remote -v

    - name: Create an issue to notify
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

